<?php return array(	
	(object) array( 
		'item_code' => 'MA2',
		'name' => 'Agriculture',
		'contact_count' => 1471,
		'item_price' => 620,
		'group_name' => 'Agriculture',
		'group_id' => 100,
	),
	(object) array( 
		'item_code' => 'MA3',
		'name' => 'Crops',
		'contact_count' => 230,
		'item_price' => 350,
		'group_name' => 'Agriculture',
		'group_id' => 100,
	),
	(object) array( 
		'item_code' => 'MA4',
		'name' => 'Farm News',
		'contact_count' => 675,
		'item_price' => 620,
		'group_name' => 'Agriculture',
		'group_id' => 100,
	),
	(object) array( 
		'item_code' => 'MA5',
		'name' => 'Forestry',
		'contact_count' => 270,
		'item_price' => 350,
		'group_name' => 'Agriculture',
		'group_id' => 100,
	),
	(object) array( 
		'item_code' => 'MA6',
		'name' => 'Livestock',
		'contact_count' => 338,
		'item_price' => 350,
		'group_name' => 'Agriculture',
		'group_id' => 100,
	),
	(object) array( 
		'item_code' => 'MA7',
		'name' => 'Tobacco',
		'contact_count' => 386,
		'item_price' => 350,
		'group_name' => 'Agriculture',
		'group_id' => 100,
	),
	(object) array( 
		'item_code' => 'MT8',
		'name' => 'Automotive Industry',
		'contact_count' => 1114,
		'item_price' => 620,
		'group_name' => 'Automotive',
		'group_id' => 103,
	),
	(object) array( 
		'item_code' => 'MT4',
		'name' => 'Automotive Repairs',
		'contact_count' => 176,
		'item_price' => 350,
		'group_name' => 'Automotive',
		'group_id' => 103,
	),
	(object) array( 
		'item_code' => 'MT5',
		'name' => 'Car & Motorcycle Accessories',
		'contact_count' => 170,
		'item_price' => 350,
		'group_name' => 'Automotive',
		'group_id' => 103,
	),
	(object) array( 
		'item_code' => 'MT6',
		'name' => 'Car & Motorcycle Mechanics',
		'contact_count' => 162,
		'item_price' => 350,
		'group_name' => 'Automotive',
		'group_id' => 103,
	),
	(object) array( 
		'item_code' => 'MT9',
		'name' => 'Electric Vehicles',
		'contact_count' => 24,
		'item_price' => 125,
		'group_name' => 'Automotive',
		'group_id' => 103,
	),
	(object) array( 
		'item_code' => 'MT7',
		'name' => 'Motorcycle Trade & Motorcycling',
		'contact_count' => 105,
		'item_price' => 125,
		'group_name' => 'Automotive',
		'group_id' => 103,
	),
	(object) array( 
		'item_code' => '544',
		'name' => 'B2B',
		'contact_count' => 40,
		'item_price' => 125,
		'group_name' => 'Business',
		'group_id' => 106,
	),
	(object) array( 
		'item_code' => 'C70',
		'name' => 'Corporate Social Responsibility',
		'contact_count' => 858,
		'item_price' => 620,
		'group_name' => 'Business',
		'group_id' => 106,
	),
	(object) array( 
		'item_code' => 'C73',
		'name' => 'Customer Relationship Management (CRM)',
		'contact_count' => 51,
		'item_price' => 125,
		'group_name' => 'Business',
		'group_id' => 106,
	),
	(object) array( 
		'item_code' => 'C71',
		'name' => 'Human Resources',
		'contact_count' => 210,
		'item_price' => 350,
		'group_name' => 'Business',
		'group_id' => 106,
	),
	(object) array( 
		'item_code' => '687',
		'name' => 'International Trade',
		'contact_count' => 74,
		'item_price' => 125,
		'group_name' => 'Business',
		'group_id' => 106,
	),
	(object) array( 
		'item_code' => '679',
		'name' => 'Market Research',
		'contact_count' => 183,
		'item_price' => 350,
		'group_name' => 'Business',
		'group_id' => 106,
	),
	(object) array( 
		'item_code' => 'C52',
		'name' => 'Outsourcing',
		'contact_count' => 79,
		'item_price' => 125,
		'group_name' => 'Business',
		'group_id' => 106,
	),
	(object) array( 
		'item_code' => 'PR1',
		'name' => 'PR/Advertising & Marketing',
		'contact_count' => 1710,
		'item_price' => 620,
		'group_name' => 'Business',
		'group_id' => 106,
	),
	(object) array( 
		'item_code' => 'C72',
		'name' => 'Small Business',
		'contact_count' => 527,
		'item_price' => 620,
		'group_name' => 'Business',
		'group_id' => 106,
	),
	(object) array( 
		'item_code' => '681',
		'name' => 'Start-Ups & Entrepreneurs',
		'contact_count' => 17,
		'item_price' => 125,
		'group_name' => 'Business',
		'group_id' => 106,
	),
	(object) array( 
		'item_code' => 'F11',
		'name' => 'Venture Capital',
		'contact_count' => 61,
		'item_price' => 125,
		'group_name' => 'Business',
		'group_id' => 106,
	),
	(object) array( 
		'item_code' => '570',
		'name' => 'Arts & Entertainment',
		'contact_count' => 1265,
		'item_price' => 620,
		'group_name' => 'College Media',
		'group_id' => 109,
	),
	(object) array( 
		'item_code' => 'GCM',
		'name' => 'General College Media',
		'contact_count' => 1344,
		'item_price' => 620,
		'group_name' => 'College Media',
		'group_id' => 109,
	),
	(object) array( 
		'item_code' => '571',
		'name' => 'Sports',
		'contact_count' => 1022,
		'item_price' => 620,
		'group_name' => 'College Media',
		'group_id' => 109,
	),
	(object) array( 
		'item_code' => 'RM3',
		'name' => 'Architecture',
		'contact_count' => 463,
		'item_price' => 620,
		'group_name' => 'Construction & Building',
		'group_id' => 112,
	),
	(object) array( 
		'item_code' => 'MK1',
		'name' => 'Civil Engineering',
		'contact_count' => 111,
		'item_price' => 125,
		'group_name' => 'Construction & Building',
		'group_id' => 112,
	),
	(object) array( 
		'item_code' => 'MK2',
		'name' => 'Construction & Building Materials',
		'contact_count' => 938,
		'item_price' => 620,
		'group_name' => 'Construction & Building',
		'group_id' => 112,
	),
	(object) array( 
		'item_code' => 'MK3',
		'name' => 'Construction Technology',
		'contact_count' => 160,
		'item_price' => 350,
		'group_name' => 'Construction & Building',
		'group_id' => 112,
	),
	(object) array( 
		'item_code' => '573',
		'name' => 'General Construction & Building',
		'contact_count' => 381,
		'item_price' => 350,
		'group_name' => 'Construction & Building',
		'group_id' => 112,
	),
	(object) array( 
		'item_code' => '682',
		'name' => 'Home and Garden',
		'contact_count' => 899,
		'item_price' => 620,
		'group_name' => 'Construction & Building',
		'group_id' => 112,
	),
	(object) array( 
		'item_code' => 'KN1',
		'name' => 'Adult Education',
		'contact_count' => 470,
		'item_price' => 620,
		'group_name' => 'Education',
		'group_id' => 115,
	),
	(object) array( 
		'item_code' => 'KN2',
		'name' => 'Children\'s Education',
		'contact_count' => 193,
		'item_price' => 350,
		'group_name' => 'Education',
		'group_id' => 115,
	),
	(object) array( 
		'item_code' => 'KN3',
		'name' => 'Education',
		'contact_count' => 1243,
		'item_price' => 620,
		'group_name' => 'Education',
		'group_id' => 115,
	),
	(object) array( 
		'item_code' => 'KN4',
		'name' => 'Higher Education',
		'contact_count' => 970,
		'item_price' => 620,
		'group_name' => 'Education',
		'group_id' => 115,
	),
	(object) array( 
		'item_code' => '683',
		'name' => 'Popular Science',
		'contact_count' => 637,
		'item_price' => 620,
		'group_name' => 'Education',
		'group_id' => 115,
	),
	(object) array( 
		'item_code' => 'KN5',
		'name' => 'Teaching',
		'contact_count' => 371,
		'item_price' => 350,
		'group_name' => 'Education',
		'group_id' => 115,
	),
	(object) array( 
		'item_code' => '684',
		'name' => 'Chemicals',
		'contact_count' => 94,
		'item_price' => 125,
		'group_name' => 'Energy',
		'group_id' => 118,
	),
	(object) array( 
		'item_code' => 'MY1',
		'name' => 'Electrical Industry',
		'contact_count' => 676,
		'item_price' => 620,
		'group_name' => 'Energy',
		'group_id' => 118,
	),
	(object) array( 
		'item_code' => 'MY2',
		'name' => 'Emergency Planning & Disaster Recovery',
		'contact_count' => 309,
		'item_price' => 350,
		'group_name' => 'Energy',
		'group_id' => 118,
	),
	(object) array( 
		'item_code' => 'MY5',
		'name' => 'Fuel, Energy & Natural Resources',
		'contact_count' => 1086,
		'item_price' => 620,
		'group_name' => 'Energy',
		'group_id' => 118,
	),
	(object) array( 
		'item_code' => 'MY3',
		'name' => 'Gas',
		'contact_count' => 187,
		'item_price' => 350,
		'group_name' => 'Energy',
		'group_id' => 118,
	),
	(object) array( 
		'item_code' => 'MY9',
		'name' => 'General Oil & Energy',
		'contact_count' => 426,
		'item_price' => 350,
		'group_name' => 'Energy',
		'group_id' => 118,
	),
	(object) array( 
		'item_code' => 'MY7',
		'name' => 'Home Heating',
		'contact_count' => 66,
		'item_price' => 125,
		'group_name' => 'Energy',
		'group_id' => 118,
	),
	(object) array( 
		'item_code' => 'MY4',
		'name' => 'Oil & Petroleum',
		'contact_count' => 355,
		'item_price' => 350,
		'group_name' => 'Energy',
		'group_id' => 118,
	),
	(object) array( 
		'item_code' => 'MY6',
		'name' => 'Power & Energy',
		'contact_count' => 766,
		'item_price' => 620,
		'group_name' => 'Energy',
		'group_id' => 118,
	),
	(object) array( 
		'item_code' => 'MY8',
		'name' => 'Utilities',
		'contact_count' => 153,
		'item_price' => 350,
		'group_name' => 'Energy',
		'group_id' => 118,
	),
	(object) array( 
		'item_code' => '563',
		'name' => 'Books',
		'contact_count' => 365,
		'item_price' => 350,
		'group_name' => 'Entertainment',
		'group_id' => 124,
	),
	(object) array( 
		'item_code' => 'ME4',
		'name' => 'Celebrity',
		'contact_count' => 621,
		'item_price' => 620,
		'group_name' => 'Entertainment',
		'group_id' => 124,
	),
	(object) array( 
		'item_code' => 'M94',
		'name' => 'Entertainment',
		'contact_count' => 1540,
		'item_price' => 620,
		'group_name' => 'Entertainment',
		'group_id' => 124,
	),
	(object) array( 
		'item_code' => '572',
		'name' => 'Fine Arts',
		'contact_count' => 1003,
		'item_price' => 620,
		'group_name' => 'Entertainment',
		'group_id' => 124,
	),
	(object) array( 
		'item_code' => 'M96',
		'name' => 'Motion Pictures',
		'contact_count' => 980,
		'item_price' => 620,
		'group_name' => 'Entertainment',
		'group_id' => 124,
	),
	(object) array( 
		'item_code' => 'M97',
		'name' => 'Music',
		'contact_count' => 1848,
		'item_price' => 620,
		'group_name' => 'Entertainment',
		'group_id' => 124,
	),
	(object) array( 
		'item_code' => 'M85',
		'name' => 'Nightclubs/Bars & Pubs',
		'contact_count' => 601,
		'item_price' => 620,
		'group_name' => 'Entertainment',
		'group_id' => 124,
	),
	(object) array( 
		'item_code' => 'M01',
		'name' => 'Publishing',
		'contact_count' => 603,
		'item_price' => 620,
		'group_name' => 'Entertainment',
		'group_id' => 124,
	),
	(object) array( 
		'item_code' => 'M93',
		'name' => 'Radio Industry',
		'contact_count' => 1008,
		'item_price' => 620,
		'group_name' => 'Entertainment',
		'group_id' => 124,
	),
	(object) array( 
		'item_code' => 'M98',
		'name' => 'Television',
		'contact_count' => 636,
		'item_price' => 620,
		'group_name' => 'Entertainment',
		'group_id' => 124,
	),
	(object) array( 
		'item_code' => '592',
		'name' => 'Theater',
		'contact_count' => 253,
		'item_price' => 350,
		'group_name' => 'Entertainment',
		'group_id' => 124,
	),
	(object) array( 
		'item_code' => 'E60',
		'name' => 'Air Pollution',
		'contact_count' => 114,
		'item_price' => 125,
		'group_name' => 'Environment',
		'group_id' => 127,
	),
	(object) array( 
		'item_code' => '685',
		'name' => 'Climate Change',
		'contact_count' => 106,
		'item_price' => 125,
		'group_name' => 'Environment',
		'group_id' => 127,
	),
	(object) array( 
		'item_code' => 'E68',
		'name' => 'Conservation',
		'contact_count' => 321,
		'item_price' => 350,
		'group_name' => 'Environment',
		'group_id' => 127,
	),
	(object) array( 
		'item_code' => 'E70',
		'name' => 'Ecology',
		'contact_count' => 127,
		'item_price' => 125,
		'group_name' => 'Environment',
		'group_id' => 127,
	),
	(object) array( 
		'item_code' => 'E61',
		'name' => 'Environment',
		'contact_count' => 1679,
		'item_price' => 620,
		'group_name' => 'Environment',
		'group_id' => 127,
	),
	(object) array( 
		'item_code' => 'E62',
		'name' => 'Environmental Engineering',
		'contact_count' => 183,
		'item_price' => 350,
		'group_name' => 'Environment',
		'group_id' => 127,
	),
	(object) array( 
		'item_code' => 'E63',
		'name' => 'Environmental Health',
		'contact_count' => 541,
		'item_price' => 620,
		'group_name' => 'Environment',
		'group_id' => 127,
	),
	(object) array( 
		'item_code' => 'E69',
		'name' => 'Global Warming',
		'contact_count' => 822,
		'item_price' => 620,
		'group_name' => 'Environment',
		'group_id' => 127,
	),
	(object) array( 
		'item_code' => 'E71',
		'name' => 'Green Technology',
		'contact_count' => 24,
		'item_price' => 125,
		'group_name' => 'Environment',
		'group_id' => 127,
	),
	(object) array( 
		'item_code' => 'E64',
		'name' => 'Marine Pollution',
		'contact_count' => 164,
		'item_price' => 350,
		'group_name' => 'Environment',
		'group_id' => 127,
	),
	(object) array( 
		'item_code' => 'E65',
		'name' => 'Pollution',
		'contact_count' => 152,
		'item_price' => 350,
		'group_name' => 'Environment',
		'group_id' => 127,
	),
	(object) array( 
		'item_code' => 'E66',
		'name' => 'Recycling',
		'contact_count' => 63,
		'item_price' => 125,
		'group_name' => 'Environment',
		'group_id' => 127,
	),
	(object) array( 
		'item_code' => 'E67',
		'name' => 'Water Treatment & Supply',
		'contact_count' => 994,
		'item_price' => 620,
		'group_name' => 'Environment',
		'group_id' => 127,
	),
	(object) array( 
		'item_code' => 'F10',
		'name' => 'Accounting',
		'contact_count' => 153,
		'item_price' => 350,
		'group_name' => 'Finance',
		'group_id' => 130,
	),
	(object) array( 
		'item_code' => 'F09',
		'name' => 'Banking',
		'contact_count' => 428,
		'item_price' => 350,
		'group_name' => 'Finance',
		'group_id' => 130,
	),
	(object) array( 
		'item_code' => 'RM1',
		'name' => 'Commercial Real Estate',
		'contact_count' => 562,
		'item_price' => 620,
		'group_name' => 'Finance',
		'group_id' => 130,
	),
	(object) array( 
		'item_code' => 'F08',
		'name' => 'E-commerce',
		'contact_count' => 19,
		'item_price' => 125,
		'group_name' => 'Finance',
		'group_id' => 130,
	),
	(object) array( 
		'item_code' => 'F07',
		'name' => 'Economics',
		'contact_count' => 886,
		'item_price' => 620,
		'group_name' => 'Finance',
		'group_id' => 130,
	),
	(object) array( 
		'item_code' => 'F06',
		'name' => 'Finance',
		'contact_count' => 2668,
		'item_price' => 620,
		'group_name' => 'Finance',
		'group_id' => 130,
	),
	(object) array( 
		'item_code' => 'F05',
		'name' => 'Financial Services',
		'contact_count' => 639,
		'item_price' => 620,
		'group_name' => 'Finance',
		'group_id' => 130,
	),
	(object) array( 
		'item_code' => 'F04',
		'name' => 'Insurance',
		'contact_count' => 566,
		'item_price' => 620,
		'group_name' => 'Finance',
		'group_id' => 130,
	),
	(object) array( 
		'item_code' => 'F03',
		'name' => 'Mortgages',
		'contact_count' => 99,
		'item_price' => 125,
		'group_name' => 'Finance',
		'group_id' => 130,
	),
	(object) array( 
		'item_code' => 'F02',
		'name' => 'Mutual Funds',
		'contact_count' => 156,
		'item_price' => 350,
		'group_name' => 'Finance',
		'group_id' => 130,
	),
	(object) array( 
		'item_code' => 'F01',
		'name' => 'Personal Finance',
		'contact_count' => 483,
		'item_price' => 620,
		'group_name' => 'Finance',
		'group_id' => 130,
	),
	(object) array( 
		'item_code' => 'RM2',
		'name' => 'Residential Real Estate',
		'contact_count' => 319,
		'item_price' => 350,
		'group_name' => 'Finance',
		'group_id' => 130,
	),
	(object) array( 
		'item_code' => 'MB4',
		'name' => 'Beverages',
		'contact_count' => 399,
		'item_price' => 350,
		'group_name' => 'Food & Beverage',
		'group_id' => 133,
	),
	(object) array( 
		'item_code' => 'MB3',
		'name' => 'Food & Diet Trends',
		'contact_count' => 49,
		'item_price' => 125,
		'group_name' => 'Food & Beverage',
		'group_id' => 133,
	),
	(object) array( 
		'item_code' => 'MB8',
		'name' => 'Food Industry',
		'contact_count' => 330,
		'item_price' => 350,
		'group_name' => 'Food & Beverage',
		'group_id' => 133,
	),
	(object) array( 
		'item_code' => 'MB2',
		'name' => 'General Food & Nutrition',
		'contact_count' => 948,
		'item_price' => 620,
		'group_name' => 'Food & Beverage',
		'group_id' => 133,
	),
	(object) array( 
		'item_code' => '582',
		'name' => 'Organic Foods',
		'contact_count' => 177,
		'item_price' => 350,
		'group_name' => 'Food & Beverage',
		'group_id' => 133,
	),
	(object) array( 
		'item_code' => 'MB6',
		'name' => 'Restaurants',
		'contact_count' => 621,
		'item_price' => 620,
		'group_name' => 'Food & Beverage',
		'group_id' => 133,
	),
	(object) array( 
		'item_code' => 'MB7',
		'name' => 'Spirits & Beer',
		'contact_count' => 409,
		'item_price' => 350,
		'group_name' => 'Food & Beverage',
		'group_id' => 133,
	),
	(object) array( 
		'item_code' => 'MB1',
		'name' => 'Wine',
		'contact_count' => 612,
		'item_price' => 620,
		'group_name' => 'Food & Beverage',
		'group_id' => 133,
	),
	(object) array( 
		'item_code' => 'MP2',
		'name' => 'Congress Policy',
		'contact_count' => 643,
		'item_price' => 620,
		'group_name' => 'Government & Policy',
		'group_id' => 136,
	),
	(object) array( 
		'item_code' => 'M6P',
		'name' => 'Economic Policy',
		'contact_count' => 26,
		'item_price' => 125,
		'group_name' => 'Government & Policy',
		'group_id' => 136,
	),
	(object) array( 
		'item_code' => 'M3P',
		'name' => 'Education Policy',
		'contact_count' => 565,
		'item_price' => 620,
		'group_name' => 'Government & Policy',
		'group_id' => 136,
	),
	(object) array( 
		'item_code' => 'M1P',
		'name' => 'Energy Policy',
		'contact_count' => 157,
		'item_price' => 350,
		'group_name' => 'Government & Policy',
		'group_id' => 136,
	),
	(object) array( 
		'item_code' => 'MP6',
		'name' => 'Environmental Policy',
		'contact_count' => 335,
		'item_price' => 350,
		'group_name' => 'Government & Policy',
		'group_id' => 136,
	),
	(object) array( 
		'item_code' => 'MP1',
		'name' => 'Foreign Affairs Policy',
		'contact_count' => 663,
		'item_price' => 620,
		'group_name' => 'Government & Policy',
		'group_id' => 136,
	),
	(object) array( 
		'item_code' => 'G3E',
		'name' => 'Foreign Press',
		'contact_count' => 480,
		'item_price' => 620,
		'group_name' => 'Government & Policy',
		'group_id' => 136,
	),
	(object) array( 
		'item_code' => 'M4P',
		'name' => 'Healthcare Policy',
		'contact_count' => 1065,
		'item_price' => 620,
		'group_name' => 'Government & Policy',
		'group_id' => 136,
	),
	(object) array( 
		'item_code' => 'M2P',
		'name' => 'Homeland Security General',
		'contact_count' => 170,
		'item_price' => 350,
		'group_name' => 'Government & Policy',
		'group_id' => 136,
	),
	(object) array( 
		'item_code' => 'MP7',
		'name' => 'Homeland Security Policy',
		'contact_count' => 59,
		'item_price' => 125,
		'group_name' => 'Government & Policy',
		'group_id' => 136,
	),
	(object) array( 
		'item_code' => 'MP4',
		'name' => 'Immigration Policy',
		'contact_count' => 402,
		'item_price' => 350,
		'group_name' => 'Government & Policy',
		'group_id' => 136,
	),
	(object) array( 
		'item_code' => 'MP9',
		'name' => 'Labor Policy',
		'contact_count' => 616,
		'item_price' => 620,
		'group_name' => 'Government & Policy',
		'group_id' => 136,
	),
	(object) array( 
		'item_code' => 'G2O',
		'name' => 'Legal Policy Microlist',
		'contact_count' => 114,
		'item_price' => 125,
		'group_name' => 'Government & Policy',
		'group_id' => 136,
	),
	(object) array( 
		'item_code' => 'G3D',
		'name' => 'Military/Armed Forces Policy',
		'contact_count' => 482,
		'item_price' => 620,
		'group_name' => 'Government & Policy',
		'group_id' => 136,
	),
	(object) array( 
		'item_code' => '688',
		'name' => 'Natural Disasters',
		'contact_count' => 135,
		'item_price' => 125,
		'group_name' => 'Government & Policy',
		'group_id' => 136,
	),
	(object) array( 
		'item_code' => 'G2Y',
		'name' => 'Op-Ed Writers/Editors',
		'contact_count' => 414,
		'item_price' => 350,
		'group_name' => 'Government & Policy',
		'group_id' => 136,
	),
	(object) array( 
		'item_code' => 'MP8',
		'name' => 'Pentagon Military Policy',
		'contact_count' => 626,
		'item_price' => 620,
		'group_name' => 'Government & Policy',
		'group_id' => 136,
	),
	(object) array( 
		'item_code' => 'G2N',
		'name' => 'Philanthropy Microlist',
		'contact_count' => 101,
		'item_price' => 125,
		'group_name' => 'Government & Policy',
		'group_id' => 136,
	),
	(object) array( 
		'item_code' => '589',
		'name' => 'Police/Public Safety & Crime',
		'contact_count' => 510,
		'item_price' => 620,
		'group_name' => 'Government & Policy',
		'group_id' => 136,
	),
	(object) array( 
		'item_code' => 'G2X',
		'name' => 'Political Talk Shows',
		'contact_count' => 1574,
		'item_price' => 620,
		'group_name' => 'Government & Policy',
		'group_id' => 136,
	),
	(object) array( 
		'item_code' => 'MPC',
		'name' => 'Presidential Campaign',
		'contact_count' => 1766,
		'item_price' => 620,
		'group_name' => 'Government & Policy',
		'group_id' => 136,
	),
	(object) array( 
		'item_code' => 'MP5',
		'name' => 'Supreme Court Policy',
		'contact_count' => 69,
		'item_price' => 125,
		'group_name' => 'Government & Policy',
		'group_id' => 136,
	),
	(object) array( 
		'item_code' => 'M5P',
		'name' => 'Technology Policy',
		'contact_count' => 321,
		'item_price' => 350,
		'group_name' => 'Government & Policy',
		'group_id' => 136,
	),
	(object) array( 
		'item_code' => '593',
		'name' => 'Urban Planning and Policy',
		'contact_count' => 38,
		'item_price' => 125,
		'group_name' => 'Government & Policy',
		'group_id' => 136,
	),
	(object) array( 
		'item_code' => 'MP3',
		'name' => 'White House Policy',
		'contact_count' => 1455,
		'item_price' => 620,
		'group_name' => 'Government & Policy',
		'group_id' => 136,
	),
	(object) array( 
		'item_code' => 'L52',
		'name' => 'AIDS/HIV',
		'contact_count' => 58,
		'item_price' => 125,
		'group_name' => 'Health & Medicine',
		'group_id' => 151,
	),
	(object) array( 
		'item_code' => '689',
		'name' => 'Addiction',
		'contact_count' => 26,
		'item_price' => 125,
		'group_name' => 'Health & Medicine',
		'group_id' => 151,
	),
	(object) array( 
		'item_code' => 'M92',
		'name' => 'Alternative Health',
		'contact_count' => 103,
		'item_price' => 125,
		'group_name' => 'Health & Medicine',
		'group_id' => 151,
	),
	(object) array( 
		'item_code' => '541',
		'name' => 'Asthma/Allergy',
		'contact_count' => 15,
		'item_price' => 125,
		'group_name' => 'Health & Medicine',
		'group_id' => 151,
	),
	(object) array( 
		'item_code' => 'L53',
		'name' => 'Biotech/Informatics',
		'contact_count' => 522,
		'item_price' => 620,
		'group_name' => 'Health & Medicine',
		'group_id' => 151,
	),
	(object) array( 
		'item_code' => 'MA8',
		'name' => 'Cannabis',
		'contact_count' => 102,
		'item_price' => 125,
		'group_name' => 'Health & Medicine',
		'group_id' => 151,
	),
	(object) array( 
		'item_code' => 'L54',
		'name' => 'Cardiology',
		'contact_count' => 98,
		'item_price' => 125,
		'group_name' => 'Health & Medicine',
		'group_id' => 151,
	),
	(object) array( 
		'item_code' => 'H03',
		'name' => 'Chiropractic',
		'contact_count' => 10,
		'item_price' => 125,
		'group_name' => 'Health & Medicine',
		'group_id' => 151,
	),
	(object) array( 
		'item_code' => 'L55',
		'name' => 'Clinical Trials',
		'contact_count' => 234,
		'item_price' => 350,
		'group_name' => 'Health & Medicine',
		'group_id' => 151,
	),
	(object) array( 
		'item_code' => 'L56',
		'name' => 'Dentistry',
		'contact_count' => 125,
		'item_price' => 125,
		'group_name' => 'Health & Medicine',
		'group_id' => 151,
	),
	(object) array( 
		'item_code' => 'L57',
		'name' => 'Dermatology',
		'contact_count' => 61,
		'item_price' => 125,
		'group_name' => 'Health & Medicine',
		'group_id' => 151,
	),
	(object) array( 
		'item_code' => 'H04',
		'name' => 'Diabetes',
		'contact_count' => 48,
		'item_price' => 125,
		'group_name' => 'Health & Medicine',
		'group_id' => 151,
	),
	(object) array( 
		'item_code' => 'L58',
		'name' => 'Diagnostics',
		'contact_count' => 316,
		'item_price' => 350,
		'group_name' => 'Health & Medicine',
		'group_id' => 151,
	),
	(object) array( 
		'item_code' => 'L59',
		'name' => 'Disability & Rehabilitation',
		'contact_count' => 26,
		'item_price' => 125,
		'group_name' => 'Health & Medicine',
		'group_id' => 151,
	),
	(object) array( 
		'item_code' => 'L61',
		'name' => 'Emergency Medicine',
		'contact_count' => 60,
		'item_price' => 125,
		'group_name' => 'Health & Medicine',
		'group_id' => 151,
	),
	(object) array( 
		'item_code' => 'L62',
		'name' => 'Endocrinology',
		'contact_count' => 23,
		'item_price' => 125,
		'group_name' => 'Health & Medicine',
		'group_id' => 151,
	),
	(object) array( 
		'item_code' => 'L64',
		'name' => 'Epidemiology',
		'contact_count' => 50,
		'item_price' => 125,
		'group_name' => 'Health & Medicine',
		'group_id' => 151,
	),
	(object) array( 
		'item_code' => 'L82',
		'name' => 'Fitness',
		'contact_count' => 812,
		'item_price' => 620,
		'group_name' => 'Health & Medicine',
		'group_id' => 151,
	),
	(object) array( 
		'item_code' => 'L65',
		'name' => 'Gastroenterology',
		'contact_count' => 21,
		'item_price' => 125,
		'group_name' => 'Health & Medicine',
		'group_id' => 151,
	),
	(object) array( 
		'item_code' => '575',
		'name' => 'General Mental Health',
		'contact_count' => 69,
		'item_price' => 125,
		'group_name' => 'Health & Medicine',
		'group_id' => 151,
	),
	(object) array( 
		'item_code' => 'L66',
		'name' => 'General Practitioners & Family Doctors',
		'contact_count' => 87,
		'item_price' => 125,
		'group_name' => 'Health & Medicine',
		'group_id' => 151,
	),
	(object) array( 
		'item_code' => 'L67',
		'name' => 'Genetics',
		'contact_count' => 88,
		'item_price' => 125,
		'group_name' => 'Health & Medicine',
		'group_id' => 151,
	),
	(object) array( 
		'item_code' => 'L68',
		'name' => 'Gerontology',
		'contact_count' => 183,
		'item_price' => 350,
		'group_name' => 'Health & Medicine',
		'group_id' => 151,
	),
	(object) array( 
		'item_code' => 'L69',
		'name' => 'Health',
		'contact_count' => 3405,
		'item_price' => 620,
		'group_name' => 'Health & Medicine',
		'group_id' => 151,
	),
	(object) array( 
		'item_code' => 'L70',
		'name' => 'Healthcare',
		'contact_count' => 2508,
		'item_price' => 620,
		'group_name' => 'Health & Medicine',
		'group_id' => 151,
	),
	(object) array( 
		'item_code' => 'L71',
		'name' => 'Hearing & Speech',
		'contact_count' => 60,
		'item_price' => 125,
		'group_name' => 'Health & Medicine',
		'group_id' => 151,
	),
	(object) array( 
		'item_code' => 'H05',
		'name' => 'Hematology',
		'contact_count' => 33,
		'item_price' => 125,
		'group_name' => 'Health & Medicine',
		'group_id' => 151,
	),
	(object) array( 
		'item_code' => 'L72',
		'name' => 'Hospitals',
		'contact_count' => 179,
		'item_price' => 350,
		'group_name' => 'Health & Medicine',
		'group_id' => 151,
	),
	(object) array( 
		'item_code' => 'L73',
		'name' => 'Immunology',
		'contact_count' => 58,
		'item_price' => 125,
		'group_name' => 'Health & Medicine',
		'group_id' => 151,
	),
	(object) array( 
		'item_code' => 'H01',
		'name' => 'Infectious Diseases',
		'contact_count' => 120,
		'item_price' => 125,
		'group_name' => 'Health & Medicine',
		'group_id' => 151,
	),
	(object) array( 
		'item_code' => 'L74',
		'name' => 'Laboratory Medicine & Equipment',
		'contact_count' => 113,
		'item_price' => 125,
		'group_name' => 'Health & Medicine',
		'group_id' => 151,
	),
	(object) array( 
		'item_code' => 'L75',
		'name' => 'Medical & Hospital Equipment',
		'contact_count' => 167,
		'item_price' => 350,
		'group_name' => 'Health & Medicine',
		'group_id' => 151,
	),
	(object) array( 
		'item_code' => 'L76',
		'name' => 'Medical Practice Management',
		'contact_count' => 138,
		'item_price' => 125,
		'group_name' => 'Health & Medicine',
		'group_id' => 151,
	),
	(object) array( 
		'item_code' => 'L77',
		'name' => 'Medical Products & Services',
		'contact_count' => 194,
		'item_price' => 350,
		'group_name' => 'Health & Medicine',
		'group_id' => 151,
	),
	(object) array( 
		'item_code' => 'L79',
		'name' => 'Men\'s Interest',
		'contact_count' => 227,
		'item_price' => 350,
		'group_name' => 'Health & Medicine',
		'group_id' => 151,
	),
	(object) array( 
		'item_code' => 'L80',
		'name' => 'Neurology',
		'contact_count' => 189,
		'item_price' => 350,
		'group_name' => 'Health & Medicine',
		'group_id' => 151,
	),
	(object) array( 
		'item_code' => 'L81',
		'name' => 'Nursing',
		'contact_count' => 238,
		'item_price' => 350,
		'group_name' => 'Health & Medicine',
		'group_id' => 151,
	),
	(object) array( 
		'item_code' => 'H06',
		'name' => 'Nutrition',
		'contact_count' => 421,
		'item_price' => 350,
		'group_name' => 'Health & Medicine',
		'group_id' => 151,
	),
	(object) array( 
		'item_code' => 'L83',
		'name' => 'Obstetrics & Gynecology',
		'contact_count' => 27,
		'item_price' => 125,
		'group_name' => 'Health & Medicine',
		'group_id' => 151,
	),
	(object) array( 
		'item_code' => 'L84',
		'name' => 'Occupational Health & Safety',
		'contact_count' => 102,
		'item_price' => 125,
		'group_name' => 'Health & Medicine',
		'group_id' => 151,
	),
	(object) array( 
		'item_code' => 'L85',
		'name' => 'Oncology',
		'contact_count' => 162,
		'item_price' => 350,
		'group_name' => 'Health & Medicine',
		'group_id' => 151,
	),
	(object) array( 
		'item_code' => 'L86',
		'name' => 'Opticians & Ophthalmology',
		'contact_count' => 74,
		'item_price' => 125,
		'group_name' => 'Health & Medicine',
		'group_id' => 151,
	),
	(object) array( 
		'item_code' => 'L87',
		'name' => 'Orthopedics',
		'contact_count' => 45,
		'item_price' => 125,
		'group_name' => 'Health & Medicine',
		'group_id' => 151,
	),
	(object) array( 
		'item_code' => 'L89',
		'name' => 'Pediatrics',
		'contact_count' => 159,
		'item_price' => 350,
		'group_name' => 'Health & Medicine',
		'group_id' => 151,
	),
	(object) array( 
		'item_code' => 'L92',
		'name' => 'Pharmaceutical & Prescription Medicine',
		'contact_count' => 141,
		'item_price' => 125,
		'group_name' => 'Health & Medicine',
		'group_id' => 151,
	),
	(object) array( 
		'item_code' => 'L90',
		'name' => 'Pharmaceutical Chemists',
		'contact_count' => 53,
		'item_price' => 125,
		'group_name' => 'Health & Medicine',
		'group_id' => 151,
	),
	(object) array( 
		'item_code' => 'L91',
		'name' => 'Pharmaceutical Industry',
		'contact_count' => 314,
		'item_price' => 350,
		'group_name' => 'Health & Medicine',
		'group_id' => 151,
	),
	(object) array( 
		'item_code' => 'H07',
		'name' => 'Pharmacies',
		'contact_count' => 34,
		'item_price' => 125,
		'group_name' => 'Health & Medicine',
		'group_id' => 151,
	),
	(object) array( 
		'item_code' => '588',
		'name' => 'Plastic Surgery',
		'contact_count' => 28,
		'item_price' => 125,
		'group_name' => 'Health & Medicine',
		'group_id' => 151,
	),
	(object) array( 
		'item_code' => 'L96',
		'name' => 'Psychiatry & Psychotherapy',
		'contact_count' => 160,
		'item_price' => 350,
		'group_name' => 'Health & Medicine',
		'group_id' => 151,
	),
	(object) array( 
		'item_code' => 'L97',
		'name' => 'Psychology',
		'contact_count' => 107,
		'item_price' => 125,
		'group_name' => 'Health & Medicine',
		'group_id' => 151,
	),
	(object) array( 
		'item_code' => 'L98',
		'name' => 'Radiology & Radiography',
		'contact_count' => 128,
		'item_price' => 125,
		'group_name' => 'Health & Medicine',
		'group_id' => 151,
	),
	(object) array( 
		'item_code' => 'L99',
		'name' => 'Respiratory Diseases',
		'contact_count' => 66,
		'item_price' => 125,
		'group_name' => 'Health & Medicine',
		'group_id' => 151,
	),
	(object) array( 
		'item_code' => '590',
		'name' => 'Rheumatology',
		'contact_count' => 13,
		'item_price' => 125,
		'group_name' => 'Health & Medicine',
		'group_id' => 151,
	),
	(object) array( 
		'item_code' => 'H09',
		'name' => 'Stem Cell Research',
		'contact_count' => 43,
		'item_price' => 125,
		'group_name' => 'Health & Medicine',
		'group_id' => 151,
	),
	(object) array( 
		'item_code' => 'H08',
		'name' => 'Surgery',
		'contact_count' => 299,
		'item_price' => 350,
		'group_name' => 'Health & Medicine',
		'group_id' => 151,
	),
	(object) array( 
		'item_code' => 'M89',
		'name' => 'Veterinary Health & Medicine',
		'contact_count' => 153,
		'item_price' => 350,
		'group_name' => 'Health & Medicine',
		'group_id' => 151,
	),
	(object) array( 
		'item_code' => 'M91',
		'name' => 'Women\'s Interest',
		'contact_count' => 759,
		'item_price' => 620,
		'group_name' => 'Health & Medicine',
		'group_id' => 151,
	),
	(object) array( 
		'item_code' => 'G2K',
		'name' => 'House Armed Services Committee',
		'contact_count' => 62,
		'item_price' => 125,
		'group_name' => 'House Committee',
		'group_id' => 145,
	),
	(object) array( 
		'item_code' => 'G2J',
		'name' => 'House Budget Committee',
		'contact_count' => 35,
		'item_price' => 125,
		'group_name' => 'House Committee',
		'group_id' => 145,
	),
	(object) array( 
		'item_code' => 'G2I',
		'name' => 'House Committee on Administration',
		'contact_count' => 8,
		'item_price' => 125,
		'group_name' => 'House Committee',
		'group_id' => 145,
	),
	(object) array( 
		'item_code' => 'G2H',
		'name' => 'House Committee on Agriculture',
		'contact_count' => 45,
		'item_price' => 125,
		'group_name' => 'House Committee',
		'group_id' => 145,
	),
	(object) array( 
		'item_code' => 'G2G',
		'name' => 'House Committee on Appropriations',
		'contact_count' => 51,
		'item_price' => 125,
		'group_name' => 'House Committee',
		'group_id' => 145,
	),
	(object) array( 
		'item_code' => 'G2F',
		'name' => 'House Committee on Education and Labor',
		'contact_count' => 38,
		'item_price' => 125,
		'group_name' => 'House Committee',
		'group_id' => 145,
	),
	(object) array( 
		'item_code' => 'G2E',
		'name' => 'House Committee on Energy and Commerce',
		'contact_count' => 48,
		'item_price' => 125,
		'group_name' => 'House Committee',
		'group_id' => 145,
	),
	(object) array( 
		'item_code' => 'G2D',
		'name' => 'House Committee on Financial Services',
		'contact_count' => 57,
		'item_price' => 125,
		'group_name' => 'House Committee',
		'group_id' => 145,
	),
	(object) array( 
		'item_code' => 'G2A',
		'name' => 'House Committee on Foreign Affairs',
		'contact_count' => 43,
		'item_price' => 125,
		'group_name' => 'House Committee',
		'group_id' => 145,
	),
	(object) array( 
		'item_code' => 'G2B',
		'name' => 'House Committee on Homeland Security',
		'contact_count' => 29,
		'item_price' => 125,
		'group_name' => 'House Committee',
		'group_id' => 145,
	),
	(object) array( 
		'item_code' => 'G1T',
		'name' => 'House Committee on Natural Resources',
		'contact_count' => 44,
		'item_price' => 125,
		'group_name' => 'House Committee',
		'group_id' => 145,
	),
	(object) array( 
		'item_code' => 'G2C',
		'name' => 'House Committee on Oversight & Government Reform',
		'contact_count' => 43,
		'item_price' => 125,
		'group_name' => 'House Committee',
		'group_id' => 145,
	),
	(object) array( 
		'item_code' => 'G1Z',
		'name' => 'House Committee on Rules',
		'contact_count' => 13,
		'item_price' => 125,
		'group_name' => 'House Committee',
		'group_id' => 145,
	),
	(object) array( 
		'item_code' => 'G1Y',
		'name' => 'House Committee on Science & Technology',
		'contact_count' => 36,
		'item_price' => 125,
		'group_name' => 'House Committee',
		'group_id' => 145,
	),
	(object) array( 
		'item_code' => 'G1X',
		'name' => 'House Committee on Small Business',
		'contact_count' => 21,
		'item_price' => 125,
		'group_name' => 'House Committee',
		'group_id' => 145,
	),
	(object) array( 
		'item_code' => 'G1W',
		'name' => 'House Committee on Standards of Official Conduct',
		'contact_count' => 10,
		'item_price' => 125,
		'group_name' => 'House Committee',
		'group_id' => 145,
	),
	(object) array( 
		'item_code' => 'G1U',
		'name' => 'House Committee on Transportation and Infrastructure',
		'contact_count' => 58,
		'item_price' => 125,
		'group_name' => 'House Committee',
		'group_id' => 145,
	),
	(object) array( 
		'item_code' => 'G1S',
		'name' => 'House Committee on Veterans\' Affairs',
		'contact_count' => 24,
		'item_price' => 125,
		'group_name' => 'House Committee',
		'group_id' => 145,
	),
	(object) array( 
		'item_code' => 'G1R',
		'name' => 'House Committee on Ways and Means',
		'contact_count' => 38,
		'item_price' => 125,
		'group_name' => 'House Committee',
		'group_id' => 145,
	),
	(object) array( 
		'item_code' => 'G1V',
		'name' => 'House Committee on the Judiciary',
		'contact_count' => 38,
		'item_price' => 125,
		'group_name' => 'House Committee',
		'group_id' => 145,
	),
	(object) array( 
		'item_code' => 'G1Q',
		'name' => 'House Permanent Select Committee on Intelligence',
		'contact_count' => 22,
		'item_price' => 125,
		'group_name' => 'House Committee',
		'group_id' => 145,
	),
	(object) array( 
		'item_code' => 'G2Z',
		'name' => 'House Select Committee on Energy Independence & Global Warming',
		'contact_count' => 15,
		'item_price' => 125,
		'group_name' => 'House Committee',
		'group_id' => 145,
	),
	(object) array( 
		'item_code' => 'G3B',
		'name' => 'Joint Committee on Library of Congress',
		'contact_count' => 10,
		'item_price' => 125,
		'group_name' => 'Joint Committees',
		'group_id' => 148,
	),
	(object) array( 
		'item_code' => 'G3C',
		'name' => 'Joint Committee on Printing',
		'contact_count' => 9,
		'item_price' => 125,
		'group_name' => 'Joint Committees',
		'group_id' => 148,
	),
	(object) array( 
		'item_code' => 'G2Q',
		'name' => 'Joint Committee on Taxation',
		'contact_count' => 10,
		'item_price' => 125,
		'group_name' => 'Joint Committees',
		'group_id' => 148,
	),
	(object) array( 
		'item_code' => 'G2P',
		'name' => 'Joint Economic Committee',
		'contact_count' => 18,
		'item_price' => 125,
		'group_name' => 'Joint Committees',
		'group_id' => 148,
	),
	(object) array( 
		'item_code' => 'G2T',
		'name' => 'U.S. House of Representatives-Democrats',
		'contact_count' => 191,
		'item_price' => 350,
		'group_name' => 'Joint Committees',
		'group_id' => 148,
	),
	(object) array( 
		'item_code' => 'G2U',
		'name' => 'U.S. House of Representatives-Republicans',
		'contact_count' => 250,
		'item_price' => 350,
		'group_name' => 'Joint Committees',
		'group_id' => 148,
	),
	(object) array( 
		'item_code' => 'G2V',
		'name' => 'U.S. Senate - Democrats',
		'contact_count' => 46,
		'item_price' => 125,
		'group_name' => 'Joint Committees',
		'group_id' => 148,
	),
	(object) array( 
		'item_code' => 'G2W',
		'name' => 'U.S. Senate - Republicans',
		'contact_count' => 51,
		'item_price' => 125,
		'group_name' => 'Joint Committees',
		'group_id' => 148,
	),
	(object) array( 
		'item_code' => 'C05',
		'name' => 'Canada Legal',
		'contact_count' => 20,
		'item_price' => 125,
		'group_name' => 'Legal',
		'group_id' => 154,
	),
	(object) array( 
		'item_code' => 'C34',
		'name' => 'Corporate Law',
		'contact_count' => 187,
		'item_price' => 350,
		'group_name' => 'Legal',
		'group_id' => 154,
	),
	(object) array( 
		'item_code' => 'C35',
		'name' => 'General Law',
		'contact_count' => 842,
		'item_price' => 620,
		'group_name' => 'Legal',
		'group_id' => 154,
	),
	(object) array( 
		'item_code' => 'C03',
		'name' => 'International Law US',
		'contact_count' => 71,
		'item_price' => 125,
		'group_name' => 'Legal',
		'group_id' => 154,
	),
	(object) array( 
		'item_code' => 'C36',
		'name' => 'Labor & Employment',
		'contact_count' => 606,
		'item_price' => 620,
		'group_name' => 'Legal',
		'group_id' => 154,
	),
	(object) array( 
		'item_code' => '577',
		'name' => 'Malpractice/Health Law',
		'contact_count' => 8,
		'item_price' => 125,
		'group_name' => 'Legal',
		'group_id' => 154,
	),
	(object) array( 
		'item_code' => 'C07',
		'name' => 'Personal Law US',
		'contact_count' => 68,
		'item_price' => 125,
		'group_name' => 'Legal',
		'group_id' => 154,
	),
	(object) array( 
		'item_code' => 'C02',
		'name' => 'Private Equity US',
		'contact_count' => 45,
		'item_price' => 125,
		'group_name' => 'Legal',
		'group_id' => 154,
	),
	(object) array( 
		'item_code' => 'C01',
		'name' => 'Taxation US',
		'contact_count' => 135,
		'item_price' => 125,
		'group_name' => 'Legal',
		'group_id' => 154,
	),
	(object) array( 
		'item_code' => 'C04',
		'name' => 'Top Legal Newspapers',
		'contact_count' => 273,
		'item_price' => 350,
		'group_name' => 'Legal',
		'group_id' => 154,
	),
	(object) array( 
		'item_code' => 'C06',
		'name' => 'Trade Regulation US',
		'contact_count' => 297,
		'item_price' => 350,
		'group_name' => 'Legal',
		'group_id' => 154,
	),
	(object) array( 
		'item_code' => 'LF5',
		'name' => 'Arab American/Islamic Interest',
		'contact_count' => 7,
		'item_price' => 125,
		'group_name' => 'Lifestyle, Society & Religion',
		'group_id' => 157,
	),
	(object) array( 
		'item_code' => 'LF6',
		'name' => 'Asian Interest',
		'contact_count' => 247,
		'item_price' => 350,
		'group_name' => 'Lifestyle, Society & Religion',
		'group_id' => 157,
	),
	(object) array( 
		'item_code' => 'LF3',
		'name' => 'Christian Interest',
		'contact_count' => 1799,
		'item_price' => 620,
		'group_name' => 'Lifestyle, Society & Religion',
		'group_id' => 157,
	),
	(object) array( 
		'item_code' => '564',
		'name' => 'Civil Rights',
		'contact_count' => 31,
		'item_price' => 125,
		'group_name' => 'Lifestyle, Society & Religion',
		'group_id' => 157,
	),
	(object) array( 
		'item_code' => 'LF4',
		'name' => 'Judaism/Jewish Interest',
		'contact_count' => 256,
		'item_price' => 350,
		'group_name' => 'Lifestyle, Society & Religion',
		'group_id' => 157,
	),
	(object) array( 
		'item_code' => 'LF1',
		'name' => 'LGBT',
		'contact_count' => 233,
		'item_price' => 350,
		'group_name' => 'Lifestyle, Society & Religion',
		'group_id' => 157,
	),
	(object) array( 
		'item_code' => '584',
		'name' => 'Parenting',
		'contact_count' => 252,
		'item_price' => 350,
		'group_name' => 'Lifestyle, Society & Religion',
		'group_id' => 157,
	),
	(object) array( 
		'item_code' => '680',
		'name' => 'Relationships',
		'contact_count' => 415,
		'item_price' => 350,
		'group_name' => 'Lifestyle, Society & Religion',
		'group_id' => 157,
	),
	(object) array( 
		'item_code' => 'LF2',
		'name' => 'Religion (All)',
		'contact_count' => 1469,
		'item_price' => 620,
		'group_name' => 'Lifestyle, Society & Religion',
		'group_id' => 157,
	),
	(object) array( 
		'item_code' => 'M88',
		'name' => 'Senior Citizen Interest',
		'contact_count' => 291,
		'item_price' => 350,
		'group_name' => 'Lifestyle, Society & Religion',
		'group_id' => 157,
	),
	(object) array( 
		'item_code' => '591',
		'name' => 'Spirituality',
		'contact_count' => 60,
		'item_price' => 125,
		'group_name' => 'Lifestyle, Society & Religion',
		'group_id' => 157,
	),
	(object) array( 
		'item_code' => 'MM9',
		'name' => 'Machinery and Equipment',
		'contact_count' => 742,
		'item_price' => 620,
		'group_name' => 'Manufacturing',
		'group_id' => 160,
	),
	(object) array( 
		'item_code' => 'MM7',
		'name' => 'Manufacturing',
		'contact_count' => 469,
		'item_price' => 620,
		'group_name' => 'Manufacturing',
		'group_id' => 160,
	),
	(object) array( 
		'item_code' => 'MM8',
		'name' => 'Manufacturing Technology',
		'contact_count' => 273,
		'item_price' => 350,
		'group_name' => 'Manufacturing',
		'group_id' => 160,
	),
	(object) array( 
		'item_code' => 'RW5',
		'name' => 'Biodiesel Fuels',
		'contact_count' => 26,
		'item_price' => 125,
		'group_name' => 'Renewable Energy',
		'group_id' => 121,
	),
	(object) array( 
		'item_code' => 'RW7',
		'name' => 'Ethanol',
		'contact_count' => 46,
		'item_price' => 125,
		'group_name' => 'Renewable Energy',
		'group_id' => 121,
	),
	(object) array( 
		'item_code' => 'RW1',
		'name' => 'Renewable Energy (All)',
		'contact_count' => 299,
		'item_price' => 350,
		'group_name' => 'Renewable Energy',
		'group_id' => 121,
	),
	(object) array( 
		'item_code' => 'RW4',
		'name' => 'Solar Power',
		'contact_count' => 344,
		'item_price' => 350,
		'group_name' => 'Renewable Energy',
		'group_id' => 121,
	),
	(object) array( 
		'item_code' => 'RW2',
		'name' => 'Water/Hydroelectric Energy',
		'contact_count' => 44,
		'item_price' => 125,
		'group_name' => 'Renewable Energy',
		'group_id' => 121,
	),
	(object) array( 
		'item_code' => 'RW3',
		'name' => 'Wind Energy',
		'contact_count' => 28,
		'item_price' => 125,
		'group_name' => 'Renewable Energy',
		'group_id' => 121,
	),
	(object) array( 
		'item_code' => 'MR8',
		'name' => 'Beauty/Cosmetics',
		'contact_count' => 698,
		'item_price' => 620,
		'group_name' => 'Retailing',
		'group_id' => 163,
	),
	(object) array( 
		'item_code' => 'MR7',
		'name' => 'Bridal',
		'contact_count' => 328,
		'item_price' => 350,
		'group_name' => 'Retailing',
		'group_id' => 163,
	),
	(object) array( 
		'item_code' => 'MR3',
		'name' => 'Clocks, Watches and Jewelry',
		'contact_count' => 59,
		'item_price' => 125,
		'group_name' => 'Retailing',
		'group_id' => 163,
	),
	(object) array( 
		'item_code' => 'MR4',
		'name' => 'Consumer Goods',
		'contact_count' => 415,
		'item_price' => 350,
		'group_name' => 'Retailing',
		'group_id' => 163,
	),
	(object) array( 
		'item_code' => 'MR5',
		'name' => 'Fashion & Apparel',
		'contact_count' => 1230,
		'item_price' => 620,
		'group_name' => 'Retailing',
		'group_id' => 163,
	),
	(object) array( 
		'item_code' => 'MR2',
		'name' => 'General Retailing',
		'contact_count' => 846,
		'item_price' => 620,
		'group_name' => 'Retailing',
		'group_id' => 163,
	),
	(object) array( 
		'item_code' => '585',
		'name' => 'Pets',
		'contact_count' => 140,
		'item_price' => 125,
		'group_name' => 'Retailing',
		'group_id' => 163,
	),
	(object) array( 
		'item_code' => 'MR1',
		'name' => 'Toys',
		'contact_count' => 1548,
		'item_price' => 620,
		'group_name' => 'Retailing',
		'group_id' => 163,
	),
	(object) array( 
		'item_code' => 'G1P',
		'name' => 'Senate Committee on Agriculture, Nutrition and Forestry',
		'contact_count' => 20,
		'item_price' => 125,
		'group_name' => 'Senate Committee',
		'group_id' => 142,
	),
	(object) array( 
		'item_code' => 'G1O',
		'name' => 'Senate Committee on Appropriations',
		'contact_count' => 30,
		'item_price' => 125,
		'group_name' => 'Senate Committee',
		'group_id' => 142,
	),
	(object) array( 
		'item_code' => 'G1N',
		'name' => 'Senate Committee on Armed Services',
		'contact_count' => 21,
		'item_price' => 125,
		'group_name' => 'Senate Committee',
		'group_id' => 142,
	),
	(object) array( 
		'item_code' => 'G1M',
		'name' => 'Senate Committee on Banking, Housing and Urban Affairs',
		'contact_count' => 22,
		'item_price' => 125,
		'group_name' => 'Senate Committee',
		'group_id' => 142,
	),
	(object) array( 
		'item_code' => 'G1L',
		'name' => 'Senate Committee on Budget',
		'contact_count' => 22,
		'item_price' => 125,
		'group_name' => 'Senate Committee',
		'group_id' => 142,
	),
	(object) array( 
		'item_code' => 'G1K',
		'name' => 'Senate Committee on Commerce, Science & Transportation',
		'contact_count' => 23,
		'item_price' => 125,
		'group_name' => 'Senate Committee',
		'group_id' => 142,
	),
	(object) array( 
		'item_code' => 'G1J',
		'name' => 'Senate Committee on Energy and Natural Resources',
		'contact_count' => 21,
		'item_price' => 125,
		'group_name' => 'Senate Committee',
		'group_id' => 142,
	),
	(object) array( 
		'item_code' => 'G1I',
		'name' => 'Senate Committee on Environment and Public Works',
		'contact_count' => 20,
		'item_price' => 125,
		'group_name' => 'Senate Committee',
		'group_id' => 142,
	),
	(object) array( 
		'item_code' => 'G1H',
		'name' => 'Senate Committee on Finance',
		'contact_count' => 26,
		'item_price' => 125,
		'group_name' => 'Senate Committee',
		'group_id' => 142,
	),
	(object) array( 
		'item_code' => 'G1G',
		'name' => 'Senate Committee on Foreign Relations',
		'contact_count' => 18,
		'item_price' => 125,
		'group_name' => 'Senate Committee',
		'group_id' => 142,
	),
	(object) array( 
		'item_code' => 'G1F',
		'name' => 'Senate Committee on Health, Education, Labor & Pensions',
		'contact_count' => 20,
		'item_price' => 125,
		'group_name' => 'Senate Committee',
		'group_id' => 142,
	),
	(object) array( 
		'item_code' => 'G1E',
		'name' => 'Senate Committee on Homeland Security & Governmental Affairs',
		'contact_count' => 15,
		'item_price' => 125,
		'group_name' => 'Senate Committee',
		'group_id' => 142,
	),
	(object) array( 
		'item_code' => 'G1D',
		'name' => 'Senate Committee on Judiciary',
		'contact_count' => 18,
		'item_price' => 125,
		'group_name' => 'Senate Committee',
		'group_id' => 142,
	),
	(object) array( 
		'item_code' => 'G1C',
		'name' => 'Senate Committee on Rules & Administration',
		'contact_count' => 17,
		'item_price' => 125,
		'group_name' => 'Senate Committee',
		'group_id' => 142,
	),
	(object) array( 
		'item_code' => 'G1B',
		'name' => 'Senate Committee on Small Business & Entrepreneurship',
		'contact_count' => 18,
		'item_price' => 125,
		'group_name' => 'Senate Committee',
		'group_id' => 142,
	),
	(object) array( 
		'item_code' => 'G1A',
		'name' => 'Senate Committee on Veterans Affairs',
		'contact_count' => 15,
		'item_price' => 125,
		'group_name' => 'Senate Committee',
		'group_id' => 142,
	),
	(object) array( 
		'item_code' => 'G99',
		'name' => 'Senate Select Committee on Intelligence',
		'contact_count' => 19,
		'item_price' => 125,
		'group_name' => 'Senate Committee',
		'group_id' => 142,
	),
	(object) array( 
		'item_code' => 'G98',
		'name' => 'Senate Special Committee on Aging',
		'contact_count' => 20,
		'item_price' => 125,
		'group_name' => 'Senate Committee',
		'group_id' => 142,
	),
	(object) array( 
		'item_code' => 'G97',
		'name' => 'Senate Special Committee on Ethics',
		'contact_count' => 6,
		'item_price' => 125,
		'group_name' => 'Senate Committee',
		'group_id' => 142,
	),
	(object) array( 
		'item_code' => 'G3A',
		'name' => 'Special Senate Committee on Indian Affairs',
		'contact_count' => 14,
		'item_price' => 125,
		'group_name' => 'Senate Committee',
		'group_id' => 142,
	),
	(object) array( 
		'item_code' => 'S72',
		'name' => 'Auto Racing',
		'contact_count' => 254,
		'item_price' => 350,
		'group_name' => 'Sports',
		'group_id' => 166,
	),
	(object) array( 
		'item_code' => 'S73',
		'name' => 'Baseball',
		'contact_count' => 356,
		'item_price' => 350,
		'group_name' => 'Sports',
		'group_id' => 166,
	),
	(object) array( 
		'item_code' => 'S74',
		'name' => 'Basketball',
		'contact_count' => 450,
		'item_price' => 350,
		'group_name' => 'Sports',
		'group_id' => 166,
	),
	(object) array( 
		'item_code' => 'S90',
		'name' => 'Boating',
		'contact_count' => 270,
		'item_price' => 350,
		'group_name' => 'Sports',
		'group_id' => 166,
	),
	(object) array( 
		'item_code' => 'S75',
		'name' => 'Cycling',
		'contact_count' => 1348,
		'item_price' => 620,
		'group_name' => 'Sports',
		'group_id' => 166,
	),
	(object) array( 
		'item_code' => 'S89',
		'name' => 'Extreme Sports',
		'contact_count' => 41,
		'item_price' => 125,
		'group_name' => 'Sports',
		'group_id' => 166,
	),
	(object) array( 
		'item_code' => 'S76',
		'name' => 'Fishing',
		'contact_count' => 638,
		'item_price' => 620,
		'group_name' => 'Sports',
		'group_id' => 166,
	),
	(object) array( 
		'item_code' => 'S77',
		'name' => 'Football',
		'contact_count' => 1466,
		'item_price' => 620,
		'group_name' => 'Sports',
		'group_id' => 166,
	),
	(object) array( 
		'item_code' => 'S78',
		'name' => 'Golf',
		'contact_count' => 336,
		'item_price' => 350,
		'group_name' => 'Sports',
		'group_id' => 166,
	),
	(object) array( 
		'item_code' => 'S79',
		'name' => 'Ice Hockey',
		'contact_count' => 108,
		'item_price' => 125,
		'group_name' => 'Sports',
		'group_id' => 166,
	),
	(object) array( 
		'item_code' => 'S80',
		'name' => 'National Sporting News',
		'contact_count' => 629,
		'item_price' => 620,
		'group_name' => 'Sports',
		'group_id' => 166,
	),
	(object) array( 
		'item_code' => 'S81',
		'name' => 'Olympics',
		'contact_count' => 980,
		'item_price' => 620,
		'group_name' => 'Sports',
		'group_id' => 166,
	),
	(object) array( 
		'item_code' => 'S82',
		'name' => 'Outdoor/Hunting',
		'contact_count' => 643,
		'item_price' => 620,
		'group_name' => 'Sports',
		'group_id' => 166,
	),
	(object) array( 
		'item_code' => 'S83',
		'name' => 'Running',
		'contact_count' => 293,
		'item_price' => 350,
		'group_name' => 'Sports',
		'group_id' => 166,
	),
	(object) array( 
		'item_code' => 'S84',
		'name' => 'Skiing',
		'contact_count' => 784,
		'item_price' => 620,
		'group_name' => 'Sports',
		'group_id' => 166,
	),
	(object) array( 
		'item_code' => 'S85',
		'name' => 'Soccer',
		'contact_count' => 492,
		'item_price' => 620,
		'group_name' => 'Sports',
		'group_id' => 166,
	),
	(object) array( 
		'item_code' => 'S86',
		'name' => 'Sports Industry',
		'contact_count' => 1198,
		'item_price' => 620,
		'group_name' => 'Sports',
		'group_id' => 166,
	),
	(object) array( 
		'item_code' => 'S87',
		'name' => 'Tennis',
		'contact_count' => 100,
		'item_price' => 125,
		'group_name' => 'Sports',
		'group_id' => 166,
	),
	(object) array( 
		'item_code' => 'S88',
		'name' => 'Watersports',
		'contact_count' => 142,
		'item_price' => 125,
		'group_name' => 'Sports',
		'group_id' => 166,
	),
	(object) array( 
		'item_code' => 'G01',
		'name' => 'Alabama',
		'contact_count' => 100,
		'item_price' => 125,
		'group_name' => 'State Policy',
		'group_id' => 139,
	),
	(object) array( 
		'item_code' => 'G02',
		'name' => 'Alaska',
		'contact_count' => 41,
		'item_price' => 125,
		'group_name' => 'State Policy',
		'group_id' => 139,
	),
	(object) array( 
		'item_code' => 'G03',
		'name' => 'Arizona',
		'contact_count' => 120,
		'item_price' => 125,
		'group_name' => 'State Policy',
		'group_id' => 139,
	),
	(object) array( 
		'item_code' => 'G04',
		'name' => 'Arkansas',
		'contact_count' => 83,
		'item_price' => 125,
		'group_name' => 'State Policy',
		'group_id' => 139,
	),
	(object) array( 
		'item_code' => 'PCA',
		'name' => 'California',
		'contact_count' => 153,
		'item_price' => 350,
		'group_name' => 'State Policy',
		'group_id' => 139,
	),
	(object) array( 
		'item_code' => 'G05',
		'name' => 'Colorado',
		'contact_count' => 256,
		'item_price' => 350,
		'group_name' => 'State Policy',
		'group_id' => 139,
	),
	(object) array( 
		'item_code' => 'G06',
		'name' => 'Connecticut',
		'contact_count' => 104,
		'item_price' => 125,
		'group_name' => 'State Policy',
		'group_id' => 139,
	),
	(object) array( 
		'item_code' => 'G07',
		'name' => 'Delaware',
		'contact_count' => 52,
		'item_price' => 125,
		'group_name' => 'State Policy',
		'group_id' => 139,
	),
	(object) array( 
		'item_code' => 'G08',
		'name' => 'Florida',
		'contact_count' => 349,
		'item_price' => 350,
		'group_name' => 'State Policy',
		'group_id' => 139,
	),
	(object) array( 
		'item_code' => 'G09',
		'name' => 'Georgia',
		'contact_count' => 303,
		'item_price' => 350,
		'group_name' => 'State Policy',
		'group_id' => 139,
	),
	(object) array( 
		'item_code' => 'G10',
		'name' => 'Hawaii',
		'contact_count' => 48,
		'item_price' => 125,
		'group_name' => 'State Policy',
		'group_id' => 139,
	),
	(object) array( 
		'item_code' => 'G11',
		'name' => 'Idaho',
		'contact_count' => 57,
		'item_price' => 125,
		'group_name' => 'State Policy',
		'group_id' => 139,
	),
	(object) array( 
		'item_code' => 'G12',
		'name' => 'Illinois',
		'contact_count' => 213,
		'item_price' => 350,
		'group_name' => 'State Policy',
		'group_id' => 139,
	),
	(object) array( 
		'item_code' => 'G13',
		'name' => 'Indiana',
		'contact_count' => 126,
		'item_price' => 125,
		'group_name' => 'State Policy',
		'group_id' => 139,
	),
	(object) array( 
		'item_code' => 'G14',
		'name' => 'Iowa',
		'contact_count' => 106,
		'item_price' => 125,
		'group_name' => 'State Policy',
		'group_id' => 139,
	),
	(object) array( 
		'item_code' => 'G15',
		'name' => 'Kansas',
		'contact_count' => 95,
		'item_price' => 125,
		'group_name' => 'State Policy',
		'group_id' => 139,
	),
	(object) array( 
		'item_code' => 'G16',
		'name' => 'Kentucky',
		'contact_count' => 153,
		'item_price' => 350,
		'group_name' => 'State Policy',
		'group_id' => 139,
	),
	(object) array( 
		'item_code' => 'G17',
		'name' => 'Louisiana',
		'contact_count' => 93,
		'item_price' => 125,
		'group_name' => 'State Policy',
		'group_id' => 139,
	),
	(object) array( 
		'item_code' => 'G18',
		'name' => 'Maine',
		'contact_count' => 52,
		'item_price' => 125,
		'group_name' => 'State Policy',
		'group_id' => 139,
	),
	(object) array( 
		'item_code' => 'G19',
		'name' => 'Maryland',
		'contact_count' => 138,
		'item_price' => 125,
		'group_name' => 'State Policy',
		'group_id' => 139,
	),
	(object) array( 
		'item_code' => 'G20',
		'name' => 'Massachusetts',
		'contact_count' => 281,
		'item_price' => 350,
		'group_name' => 'State Policy',
		'group_id' => 139,
	),
	(object) array( 
		'item_code' => 'G21',
		'name' => 'Michigan',
		'contact_count' => 90,
		'item_price' => 125,
		'group_name' => 'State Policy',
		'group_id' => 139,
	),
	(object) array( 
		'item_code' => 'G22',
		'name' => 'Minnesota',
		'contact_count' => 341,
		'item_price' => 350,
		'group_name' => 'State Policy',
		'group_id' => 139,
	),
	(object) array( 
		'item_code' => 'G23',
		'name' => 'Mississippi',
		'contact_count' => 93,
		'item_price' => 125,
		'group_name' => 'State Policy',
		'group_id' => 139,
	),
	(object) array( 
		'item_code' => 'G24',
		'name' => 'Missouri',
		'contact_count' => 142,
		'item_price' => 125,
		'group_name' => 'State Policy',
		'group_id' => 139,
	),
	(object) array( 
		'item_code' => 'G25',
		'name' => 'Montana',
		'contact_count' => 63,
		'item_price' => 125,
		'group_name' => 'State Policy',
		'group_id' => 139,
	),
	(object) array( 
		'item_code' => 'G26',
		'name' => 'Nebraska',
		'contact_count' => 132,
		'item_price' => 125,
		'group_name' => 'State Policy',
		'group_id' => 139,
	),
	(object) array( 
		'item_code' => 'G27',
		'name' => 'Nevada',
		'contact_count' => 67,
		'item_price' => 125,
		'group_name' => 'State Policy',
		'group_id' => 139,
	),
	(object) array( 
		'item_code' => 'G28',
		'name' => 'New Hampshire',
		'contact_count' => 66,
		'item_price' => 125,
		'group_name' => 'State Policy',
		'group_id' => 139,
	),
	(object) array( 
		'item_code' => 'G29',
		'name' => 'New Jersey',
		'contact_count' => 175,
		'item_price' => 350,
		'group_name' => 'State Policy',
		'group_id' => 139,
	),
	(object) array( 
		'item_code' => 'G30',
		'name' => 'New Mexico',
		'contact_count' => 63,
		'item_price' => 125,
		'group_name' => 'State Policy',
		'group_id' => 139,
	),
	(object) array( 
		'item_code' => 'MS1',
		'name' => 'New York',
		'contact_count' => 133,
		'item_price' => 125,
		'group_name' => 'State Policy',
		'group_id' => 139,
	),
	(object) array( 
		'item_code' => 'G31',
		'name' => 'North Carolina',
		'contact_count' => 198,
		'item_price' => 350,
		'group_name' => 'State Policy',
		'group_id' => 139,
	),
	(object) array( 
		'item_code' => 'G32',
		'name' => 'North Dakota',
		'contact_count' => 49,
		'item_price' => 125,
		'group_name' => 'State Policy',
		'group_id' => 139,
	),
	(object) array( 
		'item_code' => 'G33',
		'name' => 'Ohio',
		'contact_count' => 181,
		'item_price' => 350,
		'group_name' => 'State Policy',
		'group_id' => 139,
	),
	(object) array( 
		'item_code' => 'G34',
		'name' => 'Oklahoma',
		'contact_count' => 118,
		'item_price' => 125,
		'group_name' => 'State Policy',
		'group_id' => 139,
	),
	(object) array( 
		'item_code' => 'G35',
		'name' => 'Oregon',
		'contact_count' => 105,
		'item_price' => 125,
		'group_name' => 'State Policy',
		'group_id' => 139,
	),
	(object) array( 
		'item_code' => 'G36',
		'name' => 'Pennsylvania',
		'contact_count' => 380,
		'item_price' => 350,
		'group_name' => 'State Policy',
		'group_id' => 139,
	),
	(object) array( 
		'item_code' => 'G37',
		'name' => 'Rhode Island',
		'contact_count' => 71,
		'item_price' => 125,
		'group_name' => 'State Policy',
		'group_id' => 139,
	),
	(object) array( 
		'item_code' => 'G38',
		'name' => 'South Carolina',
		'contact_count' => 162,
		'item_price' => 350,
		'group_name' => 'State Policy',
		'group_id' => 139,
	),
	(object) array( 
		'item_code' => 'G39',
		'name' => 'South Dakota',
		'contact_count' => 55,
		'item_price' => 125,
		'group_name' => 'State Policy',
		'group_id' => 139,
	),
	(object) array( 
		'item_code' => 'G40',
		'name' => 'Tennessee',
		'contact_count' => 170,
		'item_price' => 350,
		'group_name' => 'State Policy',
		'group_id' => 139,
	),
	(object) array( 
		'item_code' => 'G41',
		'name' => 'Texas',
		'contact_count' => 279,
		'item_price' => 350,
		'group_name' => 'State Policy',
		'group_id' => 139,
	),
	(object) array( 
		'item_code' => 'G42',
		'name' => 'Utah',
		'contact_count' => 56,
		'item_price' => 125,
		'group_name' => 'State Policy',
		'group_id' => 139,
	),
	(object) array( 
		'item_code' => 'G43',
		'name' => 'Vermont',
		'contact_count' => 83,
		'item_price' => 125,
		'group_name' => 'State Policy',
		'group_id' => 139,
	),
	(object) array( 
		'item_code' => 'G44',
		'name' => 'Virginia',
		'contact_count' => 424,
		'item_price' => 350,
		'group_name' => 'State Policy',
		'group_id' => 139,
	),
	(object) array( 
		'item_code' => 'G45',
		'name' => 'Washington',
		'contact_count' => 202,
		'item_price' => 350,
		'group_name' => 'State Policy',
		'group_id' => 139,
	),
	(object) array( 
		'item_code' => 'G46',
		'name' => 'Washington DC',
		'contact_count' => 554,
		'item_price' => 620,
		'group_name' => 'State Policy',
		'group_id' => 139,
	),
	(object) array( 
		'item_code' => 'G47',
		'name' => 'West Virginia',
		'contact_count' => 98,
		'item_price' => 125,
		'group_name' => 'State Policy',
		'group_id' => 139,
	),
	(object) array( 
		'item_code' => 'G48',
		'name' => 'Wisconsin',
		'contact_count' => 149,
		'item_price' => 125,
		'group_name' => 'State Policy',
		'group_id' => 139,
	),
	(object) array( 
		'item_code' => 'G49',
		'name' => 'Wyoming',
		'contact_count' => 52,
		'item_price' => 125,
		'group_name' => 'State Policy',
		'group_id' => 139,
	),
	(object) array( 
		'item_code' => 'M3T',
		'name' => 'Air Freight',
		'contact_count' => 87,
		'item_price' => 125,
		'group_name' => 'Technology',
		'group_id' => 169,
	),
	(object) array( 
		'item_code' => 'V06',
		'name' => 'Airlines',
		'contact_count' => 251,
		'item_price' => 350,
		'group_name' => 'Technology',
		'group_id' => 169,
	),
	(object) array( 
		'item_code' => 'L18',
		'name' => 'Application Service Providers',
		'contact_count' => 57,
		'item_price' => 125,
		'group_name' => 'Technology',
		'group_id' => 169,
	),
	(object) array( 
		'item_code' => 'C39',
		'name' => 'Broadband Communication',
		'contact_count' => 449,
		'item_price' => 350,
		'group_name' => 'Technology',
		'group_id' => 169,
	),
	(object) array( 
		'item_code' => 'V01',
		'name' => 'Business Travel',
		'contact_count' => 136,
		'item_price' => 125,
		'group_name' => 'Technology',
		'group_id' => 169,
	),
	(object) array( 
		'item_code' => 'L41',
		'name' => 'Cable & Satellite Communications',
		'contact_count' => 408,
		'item_price' => 350,
		'group_name' => 'Technology',
		'group_id' => 169,
	),
	(object) array( 
		'item_code' => 'MR6',
		'name' => 'Children & Youth Fashion',
		'contact_count' => 236,
		'item_price' => 350,
		'group_name' => 'Technology',
		'group_id' => 169,
	),
	(object) array( 
		'item_code' => 'KN6',
		'name' => 'Children\'s Books',
		'contact_count' => 108,
		'item_price' => 125,
		'group_name' => 'Technology',
		'group_id' => 169,
	),
	(object) array( 
		'item_code' => 'KN7',
		'name' => 'Children\'s Interest',
		'contact_count' => 519,
		'item_price' => 620,
		'group_name' => 'Technology',
		'group_id' => 169,
	),
	(object) array( 
		'item_code' => '569',
		'name' => 'Cloud Computing',
		'contact_count' => 161,
		'item_price' => 350,
		'group_name' => 'Technology',
		'group_id' => 169,
	),
	(object) array( 
		'item_code' => 'C40',
		'name' => 'Computer Hardware',
		'contact_count' => 446,
		'item_price' => 350,
		'group_name' => 'Technology',
		'group_id' => 169,
	),
	(object) array( 
		'item_code' => 'C41',
		'name' => 'Computing Architecture',
		'contact_count' => 102,
		'item_price' => 125,
		'group_name' => 'Technology',
		'group_id' => 169,
	),
	(object) array( 
		'item_code' => 'M99',
		'name' => 'Consumer Electronics',
		'contact_count' => 618,
		'item_price' => 620,
		'group_name' => 'Technology',
		'group_id' => 169,
	),
	(object) array( 
		'item_code' => 'C42',
		'name' => 'Content Management & Syndication',
		'contact_count' => 333,
		'item_price' => 350,
		'group_name' => 'Technology',
		'group_id' => 169,
	),
	(object) array( 
		'item_code' => 'C43',
		'name' => 'Data Storage & Management',
		'contact_count' => 230,
		'item_price' => 350,
		'group_name' => 'Technology',
		'group_id' => 169,
	),
	(object) array( 
		'item_code' => 'L01',
		'name' => 'Digital Cameras & Access.',
		'contact_count' => 403,
		'item_price' => 350,
		'group_name' => 'Technology',
		'group_id' => 169,
	),
	(object) array( 
		'item_code' => 'L33',
		'name' => 'E-mail & Messaging',
		'contact_count' => 696,
		'item_price' => 620,
		'group_name' => 'Technology',
		'group_id' => 169,
	),
	(object) array( 
		'item_code' => 'C46',
		'name' => 'ERP',
		'contact_count' => 65,
		'item_price' => 125,
		'group_name' => 'Technology',
		'group_id' => 169,
	),
	(object) array( 
		'item_code' => 'L49',
		'name' => 'Electronic & Internet Commerce',
		'contact_count' => 122,
		'item_price' => 125,
		'group_name' => 'Technology',
		'group_id' => 169,
	),
	(object) array( 
		'item_code' => 'L12',
		'name' => 'Electronics & Components',
		'contact_count' => 817,
		'item_price' => 620,
		'group_name' => 'Technology',
		'group_id' => 169,
	),
	(object) array( 
		'item_code' => 'C44',
		'name' => 'Electronics Supply & Manufacturing',
		'contact_count' => 296,
		'item_price' => 350,
		'group_name' => 'Technology',
		'group_id' => 169,
	),
	(object) array( 
		'item_code' => 'C45',
		'name' => 'Embedded Technology',
		'contact_count' => 94,
		'item_price' => 125,
		'group_name' => 'Technology',
		'group_id' => 169,
	),
	(object) array( 
		'item_code' => 'L46',
		'name' => 'Games',
		'contact_count' => 479,
		'item_price' => 620,
		'group_name' => 'Technology',
		'group_id' => 169,
	),
	(object) array( 
		'item_code' => 'V10',
		'name' => 'Gaming & Casinos',
		'contact_count' => 933,
		'item_price' => 620,
		'group_name' => 'Technology',
		'group_id' => 169,
	),
	(object) array( 
		'item_code' => 'C74',
		'name' => 'General Technology',
		'contact_count' => 1827,
		'item_price' => 620,
		'group_name' => 'Technology',
		'group_id' => 169,
	),
	(object) array( 
		'item_code' => '576',
		'name' => 'General Transportation',
		'contact_count' => 298,
		'item_price' => 350,
		'group_name' => 'Technology',
		'group_id' => 169,
	),
	(object) array( 
		'item_code' => 'L03',
		'name' => 'Handheld Devices & Access.',
		'contact_count' => 68,
		'item_price' => 125,
		'group_name' => 'Technology',
		'group_id' => 169,
	),
	(object) array( 
		'item_code' => 'C47',
		'name' => 'Interactive Media',
		'contact_count' => 157,
		'item_price' => 350,
		'group_name' => 'Technology',
		'group_id' => 169,
	),
	(object) array( 
		'item_code' => 'L38',
		'name' => 'Internet Security',
		'contact_count' => 273,
		'item_price' => 350,
		'group_name' => 'Technology',
		'group_id' => 169,
	),
	(object) array( 
		'item_code' => 'L51',
		'name' => 'Linux',
		'contact_count' => 19,
		'item_price' => 125,
		'group_name' => 'Technology',
		'group_id' => 169,
	),
	(object) array( 
		'item_code' => 'V02',
		'name' => 'Luxury Vacations',
		'contact_count' => 146,
		'item_price' => 125,
		'group_name' => 'Technology',
		'group_id' => 169,
	),
	(object) array( 
		'item_code' => 'L22',
		'name' => 'Mobile & Wireless Communication',
		'contact_count' => 235,
		'item_price' => 350,
		'group_name' => 'Technology',
		'group_id' => 169,
	),
	(object) array( 
		'item_code' => '580',
		'name' => 'Mobile Apps',
		'contact_count' => 64,
		'item_price' => 125,
		'group_name' => 'Technology',
		'group_id' => 169,
	),
	(object) array( 
		'item_code' => 'C48',
		'name' => 'Nanotechnology',
		'contact_count' => 69,
		'item_price' => 125,
		'group_name' => 'Technology',
		'group_id' => 169,
	),
	(object) array( 
		'item_code' => 'C49',
		'name' => 'Network Security & Privacy Protection',
		'contact_count' => 836,
		'item_price' => 620,
		'group_name' => 'Technology',
		'group_id' => 169,
	),
	(object) array( 
		'item_code' => 'C51',
		'name' => 'Networking & Telecomm',
		'contact_count' => 875,
		'item_price' => 620,
		'group_name' => 'Technology',
		'group_id' => 169,
	),
	(object) array( 
		'item_code' => '672',
		'name' => 'New Media',
		'contact_count' => 167,
		'item_price' => 350,
		'group_name' => 'Technology',
		'group_id' => 169,
	),
	(object) array( 
		'item_code' => 'V03',
		'name' => 'Overseas Travel',
		'contact_count' => 125,
		'item_price' => 125,
		'group_name' => 'Technology',
		'group_id' => 169,
	),
	(object) array( 
		'item_code' => 'V04',
		'name' => 'Package Vacations',
		'contact_count' => 191,
		'item_price' => 350,
		'group_name' => 'Technology',
		'group_id' => 169,
	),
	(object) array( 
		'item_code' => 'C53',
		'name' => 'Peripherals & Accessories',
		'contact_count' => 70,
		'item_price' => 125,
		'group_name' => 'Technology',
		'group_id' => 169,
	),
	(object) array( 
		'item_code' => 'C54',
		'name' => 'Personal & Laptop Computing',
		'contact_count' => 1209,
		'item_price' => 620,
		'group_name' => 'Technology',
		'group_id' => 169,
	),
	(object) array( 
		'item_code' => 'C55',
		'name' => 'Portable Memory',
		'contact_count' => 118,
		'item_price' => 125,
		'group_name' => 'Technology',
		'group_id' => 169,
	),
	(object) array( 
		'item_code' => 'C56',
		'name' => 'Process, Manufacturing & Industrial Controls',
		'contact_count' => 62,
		'item_price' => 125,
		'group_name' => 'Technology',
		'group_id' => 169,
	),
	(object) array( 
		'item_code' => 'L45',
		'name' => 'Processors, Chips & Semiconductors',
		'contact_count' => 469,
		'item_price' => 620,
		'group_name' => 'Technology',
		'group_id' => 169,
	),
	(object) array( 
		'item_code' => 'M4T',
		'name' => 'Shipping and Marine',
		'contact_count' => 204,
		'item_price' => 350,
		'group_name' => 'Technology',
		'group_id' => 169,
	),
	(object) array( 
		'item_code' => 'C57',
		'name' => 'Systems Management',
		'contact_count' => 96,
		'item_price' => 125,
		'group_name' => 'Technology',
		'group_id' => 169,
	),
	(object) array( 
		'item_code' => 'L25',
		'name' => 'Systems Software',
		'contact_count' => 48,
		'item_price' => 125,
		'group_name' => 'Technology',
		'group_id' => 169,
	),
	(object) array( 
		'item_code' => 'V05',
		'name' => 'Touring Holidays',
		'contact_count' => 138,
		'item_price' => 125,
		'group_name' => 'Technology',
		'group_id' => 169,
	),
	(object) array( 
		'item_code' => 'V07',
		'name' => 'Tourism',
		'contact_count' => 847,
		'item_price' => 620,
		'group_name' => 'Technology',
		'group_id' => 169,
	),
	(object) array( 
		'item_code' => 'M2T',
		'name' => 'Train-Railroad',
		'contact_count' => 537,
		'item_price' => 620,
		'group_name' => 'Technology',
		'group_id' => 169,
	),
	(object) array( 
		'item_code' => 'V08',
		'name' => 'Travel',
		'contact_count' => 1200,
		'item_price' => 620,
		'group_name' => 'Technology',
		'group_id' => 169,
	),
	(object) array( 
		'item_code' => 'V09',
		'name' => 'Travel Trade & Tourism',
		'contact_count' => 1240,
		'item_price' => 620,
		'group_name' => 'Technology',
		'group_id' => 169,
	),
	(object) array( 
		'item_code' => 'M1T',
		'name' => 'Trucking',
		'contact_count' => 207,
		'item_price' => 350,
		'group_name' => 'Technology',
		'group_id' => 169,
	),
	(object) array( 
		'item_code' => 'SM1',
		'name' => 'Web 2.0/Social Media',
		'contact_count' => 138,
		'item_price' => 125,
		'group_name' => 'Technology',
		'group_id' => 169,
	),
	(object) array( 
		'item_code' => 'C58',
		'name' => 'Web Programming',
		'contact_count' => 70,
		'item_price' => 125,
		'group_name' => 'Technology',
		'group_id' => 169,
	),
	(object) array( 
		'item_code' => 'L42',
		'name' => 'Windows',
		'contact_count' => 36,
		'item_price' => 125,
		'group_name' => 'Technology',
		'group_id' => 169,
	),
	(object) array( 
		'item_code' => 'KN8',
		'name' => 'Youth Interest',
		'contact_count' => 660,
		'item_price' => 620,
		'group_name' => 'Technology',
		'group_id' => 169,
	),
);
