<?php if ($ci->is_development()) return; ?>
<?php if (Auth::is_from_secret()) return; ?>
<?php if (Auth::is_admin_mode()) return; ?>

<script>

var _kmq = _kmq || [];
var _kmk = _kmk || <?= json_encode($ci->conf('kissmetrics', 'api_key')) ?>;

// use the ID generated by our library (or the email if available)
_kmq.push(["identify", <?= json_encode(KissMetrics_Process::__identity()) ?>]);

function _kms(u) {
	setTimeout(function() {
		var d = document, f = d.getElementsByTagName("script")[0],
		s = d.createElement("script");
		s.async = true; s.src = u;
		f.parentNode.insertBefore(s, f);
	}, 1);
}

_kms("//i.kissmetrics.com/i.js");
_kms("//doug1izaerwt3.cloudfront.net/" + _kmk + ".1.js");

</script>

<noscript>
	<img src="//trk.kissmetrics.com/s?_k=<?=
		$vd->esc($ci->conf('kissmetrics', 'api_key')); ?>&amp;_p=<?= 
		$vd->esc(rawurlencode(KissMetrics_Process::__identity())) ?>&amp;JS+Disabled=Yes" />
</noscript>