#!/usr/bin/php
<?php

chdir(dirname(__FILE__));

require 'vendor/autoload.php';

if ($argc < 2)
{
	echo 'usage: create model <table> [<name>]';
	echo PHP_EOL;
	exit(1);
}

$tableName = $argv[1];
$modelName = @$argv[2];

if (!$modelName && preg_match('#^[a-z0-9]+_(.+)$#i', $tableName, $m))
	$modelName = ucwords(preg_replace('#[^a-z0-9]#i', '_', $m[1]), '_');

if (!$modelName)
{
	echo 'usage: create model <table> <name>';
	echo PHP_EOL;
	exit(2);
}

$className = sprintf('Model_%s', $modelName);
$template = file_get_contents('template.mustache');
$engine = new Mustache_Engine();
$source = $engine->render($template, array(
	'className' => $className,
	'tableName' => $tableName,
));

$fileName = sprintf('%s.php', strtolower($modelName));
$filePath = sprintf('../../application/models/%s', $fileName);

if (file_exists($filePath))
{
	echo 'error: file exists: ';
	echo sprintf('application/models/%s', $fileName);
	echo PHP_EOL;
	exit(3);
}

file_put_contents($filePath, $source);
echo sprintf('created: application/models/%s', $fileName);
echo PHP_EOL;

exit(0);